[model]
    name = "1"
    output_dir = "2"
    version = "3"

    # this field is optional it's just there for the user to know who created the model
    [author]
    author = "4"
    email = "5"

    [github]
    repo = "6"

        